name: gather weather daily

#when it should run
on:
  schedule:
    - cron: "30 6 * * *" #run everyday at utc 6:30
  push:
    branches: main #run when files updated manually

#create jobs    
jobs:
  weather: 
    runs-on: windows-latest
    
    steps: 

    # load repo
    - uses: actions/checkout@master

    # setup r
    - uses: r-lib/actions/setup-r@master

    # install packages
    - name: Install packages
      run: |
        install.packages("magrittr")
        install.packages("dplyr")
        install.packages("tibble")
        install.packages("rvest")
        install.packages("lubridate")
      shell: Rscript {0}

    - name: Scrape and compile weather
      run: |
        source('R/obs_weather_scrape.R')
        source('R/for_weather_scrape.R')
      shell: Rscript {0}
      
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add datastore/*
        git commit -am "gh action weather grab $(date)"
        git push origin main
    

  
