name: gather weather daily

#when it should run
on:
  #schedule:
    #- cron: "30 6 * * *" #run everyday at utc 6:30
  push:
    branches: main

#create jobs    
jobs:
  weather: 
    runs-on: windows-2016
    steps: 
    # load repo
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master
    #install packages
    - name: Install packages
      run: |
        Rscript -e 'install.packages("remotes")'
        Rscript -e 'remotes::install_cran("tidyverse")'
        Rscript -e 'remotes::install_cran("rvest")'
    - name: Scrape and compile weather
      run: |
        Rscript obs_weather_scrape.R
        Rscript pred_weather_scrape.R
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add datastore/*
        git commit -am "gh action weather grab $(date)"
        git push origin main
      env: 
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
    

  
